"""migration for assigning clients to a db

Revision ID: 12a99eeb9c9e
Revises: 8a08da1b15c1
Create Date: 2023-02-28 18:27:29.754507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12a99eeb9c9e'
down_revision = '8a08da1b15c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_trading_bonds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_assigned', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_trading_bonds')
    # ### end Alembic commands ###
