"""empty message

Revision ID: 1de93ad5df28
Revises: e021af79b5aa
Create Date: 2023-02-28 20:20:37.157487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1de93ad5df28'
down_revision = 'e021af79b5aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('assigned_client',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('assigned_client',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
