"""added verified records table

Revision ID: 2aac627c6099
Revises: 77a45f22cca9
Create Date: 2023-03-06 21:32:42.529781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aac627c6099'
down_revision = '77a45f22cca9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verified_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_initiated', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('has_payed', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('date_initiated', sa.DateTime(), nullable=False),
    sa.Column('date_verified', sa.DateTime(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_verified_records_client_id_clients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verified_records'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verified_records')
    # ### end Alembic commands ###
