"""updated the clients model

Revision ID: 7e568faa5730
Revises: c4cddd0a98ce
Create Date: 2023-02-28 20:07:18.739052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e568faa5730'
down_revision = 'c4cddd0a98ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_constraint('fk_admins_assigned_user_clients', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_admins_assigned_user_clients', 'clients', ['assigned_user'], ['id'])

    # ### end Alembic commands ###
