"""removed client_trading model

Revision ID: c4cddd0a98ce
Revises: 09951299b303
Create Date: 2023-02-28 18:56:21.238324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4cddd0a98ce'
down_revision = '09951299b303'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_user', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_admins_email'), ['email'])
        batch_op.create_foreign_key(batch_op.f('fk_admins_assigned_user_clients'), 'clients', ['assigned_user'], ['id'])

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_clients_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_clients_idcard_number'), ['idcard_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_clients_idcard_number'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_clients_email'), type_='unique')

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_admins_assigned_user_clients'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_admins_email'), type_='unique')
        batch_op.drop_column('assigned_user')

    # ### end Alembic commands ###
