"""minor tweak with assigned_user name

Revision ID: e021af79b5aa
Revises: 7e568faa5730
Create Date: 2023-02-28 20:16:01.070588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e021af79b5aa'
down_revision = '7e568faa5730'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_client', sa.Integer(), nullable=False))
        batch_op.drop_column('assigned_user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_user', sa.INTEGER(), nullable=False))
        batch_op.drop_column('assigned_client')

    # ### end Alembic commands ###
